# Generated by Django 4.2.2 on 2023-06-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotreModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
